### ISSUE TITLE
Compatibilidade com Lazarus

### ISSUE THREAD

**Issue by elidorio** [infussolucoes/usercontrol-sd#1]
Olá Amigos,

Verifica a possibilidade de compatibilizar o UC com Lazarus. Séria muito interessante.

Obrigado,

Edson

**Comment by infussolucoes** [comment]
Realmente é uma boa ideia. Acredito ser possível, e vamos recrutar pessoas interessadas para iniciar os testes.

**Comment by infussolucoes** [comment]
Estamos entrando em contato com o pessoal do https://github.com/jbsolucoes/ucp,
eles tem uma versão para lazarus.

Vamos propor uma unificação dos projetos.

**Comment by elidorio** [comment]
Tem alguma novidade?

**Comment by infussolucoes** [comment]
Já estamos realizando estudos para tornar compatível.

**Comment by elidorio** [comment]
E ai mais alguma novidades?

**Comment by infussolucoes** [comment]
Nada, não tivemos retorno do pessoal.


Por hora só encontrei o https://github.com/jbsolucoes/ucp.

**Comment by infussolucoes** [comment]
Pessoal, criamos a primeira versão compatível com Lazarus hoje, ela ainda necessita de testes,
mas ao menos já é possível instalar no lazarus e já disponibilizamos um exemplo com Zeos Connector.
