### ISSUE TITLE
Não consigo instalar o controle de usuário de um PC com 64-bit delphi 10,2

### ISSUE THREAD

**Issue by ricar96** [infussolucoes/usercontrol-sd#14]
Não consigo instalar o controle de usuário de um PC com 64-bit delphi 10,2 .... eu apreciaria me ajudar a realizar nesta ... como Delphi e o sistema é 64its o que eu faço é compilar e, em seguida, instalar, mas não Eu aparecer em qualquer paleta de componentes e da instalação me diz Erro ao compilar ou Pacote "pckUCDataConnector.dpk". Aguardo a sua resposta ... obrigado

**Comment by infussolucoes** [comment]
Tente instalar na versão 32 bits e somente adicionar no library path 64x do delphi os caminhos do UserControl. Então sete a aplicação para 64 bits. A princípio irá compilar normalmente.

Semelhante ao funcionamento do Fortes Report ou ACBr.
