### ISSUE TITLE
Filtro por texto nos logs

### ISSUE THREAD

**Issue by giovani7cruz** [infussolucoes/usercontrol-sd#18]
Hoje não há opção para fazer uma busca por texto nos logs gerados,
o que torna complicada a analise quando há muitos registros para analisar.

Penso ser interessante um mecanismo que possibilite este tipo de filtragem.

**Comment by infussolucoes** [comment]
Este item foi implementado por Cassianobs com uma pequena correção de Giovani_da_cruz.
