### ISSUE TITLE
Seleção de Permissões

### ISSUE THREAD

**Issue by giovani7cruz** [infussolucoes/usercontrol-sd#20]
Sugiro criar dois botões nas telas onde é possível conceder ou remover acessos.

Um botão será para abrir todos os itens da árvore.

Outro para contrair-los.

Acredito que isto facilitará a manipulação dos acessos.

**Comment by infussolucoes** [comment]
Implementação por Cassianobs.

Adicionado as opções de expandir e contrair as árvores.

Para acessar as opções, clique com o botão direito do mouse
em cima da árvore que esteja manipulando.
