### ISSUE TITLE
Melhorias no Logs do UserControl

### ISSUE THREAD

**Issue by giovani7cruz** [infussolucoes/usercontrol-sd#21]
O botão Filtrar a meu ver deverá ficar sempre habilitado.

Outra questão que ajudará bastante é poder ordenar os logs
pelas colunas do Grid, tanto em forma crescente quanto decrescente.

**Comment by infussolucoes** [comment]
Por hora foi realizado para o connector com Firedac.

Implementação realizada por Cassianobs.

**Comment by infussolucoes** [comment]
Adicionado a ordenação nos logs para os connector
DataSnap, Zeos, ADO, DBX, Midas e Rest connector.
