### ISSUE TITLE
Melhorias na tela de usuários logados.

### ISSUE THREAD

**Issue by giovani7cruz** [infussolucoes/usercontrol-sd#22]
Penso ser importante a adição de dois botões nesta tela.

Um é o Excluir e outro é o Excluir Todos.

Ambos têm a função de ajudar na manutenção para os casos 
em que não foi possível que o UserControl removesse o usuário logado.

**Comment by infussolucoes** [comment]
Adicionado as duas funções por cassianobs.

Clicando com o direito da grade de usuários logados, há duas opções:
Excluir e Excluir todos.

Excluir remove um único registro, desde que não seja o usuário atual.

Excluir Todos, remove todos os registros, com exceção do usuário atual.
