### ISSUE TITLE
Filtros e Ordenação na grade de usuários

### ISSUE THREAD

**Issue by giovani7cruz** [infussolucoes/usercontrol-sd#23]
Uma opção que pode ajudar é poder filtrar por Nome, login ou e-mail.

Também poder ordenar clicando na grade vai ajudar muito para os casos em que há
muitos usuários.

**Comment by infussolucoes** [comment]
Agora na tela de usuários há opções de filtros por login, nome ou e-mail.

Implementado por cassianobs.
