### ISSUE TITLE
Erros na instalação 

### ISSUE THREAD

**Issue by StalinBR** [infussolucoes/usercontrol-sd#3]
Ao executar o instalador, ele para no erro: 

`Embarcadero Delphi for Win32 compiler version 28.0
Copyright (c) 1983,2014 Embarcadero Technologies, Inc.
C:\usercontrol-sd-master\source\Base\MsgsForm_U.pas(96) Fatal: F1026 File not found: 'C:\usercontrol-sd-master\Packages\Base\System.ImageList.dcu'
Compilation failure
Erro ao compilar o pacote "pckUserControl_RT.dpk".`
[log_Delphi_XE7.txt](https://github.com/infussolucoes/usercontrol-sd/files/184807/log_Delphi_XE7.txt)

E ao tentar compilar os pacotes manualmente os packages aparecem com: 
rrequires ocontais  e no final 'd.' 

As units com os uses: 
  Buttons,  Controls,  Dialogs,  ExtCtrls,  Forms,  Graphics,  StdCtrls,  ComCtrls,
reclamam a falta de um namespace (eu tive que colocar "Vcl." na frente para compilar, mas não sei se é o correto a se fazer)

**Comment by infussolucoes** [comment]
Seguinte a unit ImageList não existe no XE7, para testar, tente simplesmente comentar ela e tentar novamente com o instalador.

Sempre que for utilizado o instalador, precisa remover os arquivos antigos gerados. (bpl, dcu e etc).

Vamos ver para tratar isso com uma diretiva de compilação.

**Comment by StalinBR** [comment]
Obrigado. Você tem razão. 

Nos fontes está assim: 

>   // Delphi XE 8 ou superior
  {$IFDEF DELPHI21_UP}

Mas a versão 21 é o XE7, então o certo seria DELPHI22_UP. Ai sim seria XE8 ou superior.

**Comment by infussolucoes** [comment]
Hum, verdade, tente só ajustar a diretiva e instalar pelo instalador. Se der certo, já subo a alteração.

**Comment by StalinBR** [comment]
Deu certo. Obrigado.
