### ISSUE TITLE
Recuperar imagem Usuário

### ISSUE THREAD

**Issue by rafaelsabino** [infussolucoes/usercontrol-sd#31]
Boa tarde, como faço pra recuperar os dados da imagem do usuário que é salvo na tabela do banco de dados? 

Já fiz vários tipos de consulta do tipo blob e em todas não consigo retornar a imagem salva no bd. 

Gostaria de ajuda para conseguir retornar com a mesma.

**Comment by Cassiano-Baltazar** [comment]
na tabela users tem um field chamado image/imagem, não lembro mais.
Nele tem a imagem em base64. você terá que converter a string gravada neste field em imagem.

**Comment by rafaelsabino** [comment]
Obrigado Cassiano, tentei converter também em qry string porem sem sucesso. Realmente usa base64 na tabela UCImage porém não consigo exibir o mesmo em um TImage de forma alguma :/

**Comment by Cassiano-Baltazar** [comment]
na unit IncUser_U.pas tem a conversão de base64 para um image.

**Comment by rafaelsabino** [comment]
Obrigado Cassiano, realmente, consegui a variável dps de muito custo consegui recuperar a imagem do usuário.

Caso alguém tenha curiosidade, o procedimento anexado.

O processo é o seguinte:
1º Adicionar as Uses informadas no arquivo;
2º Declarar a function Base64ToImage(Base64: string): TOleGraphic;
3º Declarar a function Base64ToStream(Value: String): TBytesStream;
4º Declarar a UnpackStream(Value: TMemoryStream): TMemoryStream;

Buscar o usuário no banco de acordo com critério de ID ou qualquer um que achar melhor. 
Buscar FDQuery com o campo da imagem e referenciar no og

Assim consegue recuperar a imagem do banco de acordo com o usuário selecionado no critério.
Abs.
[RecuperarImagemUser.zip](https://github.com/infussolucoes/usercontrol-sd/files/3759241/RecuperarImagemUser.zip)
