### ISSUE TITLE
Error when user edited

### ISSUE THREAD

**Issue by mletzel** [infussolucoes/usercontrol-sd#32]
When I edit user (Change User - Alter) there is an error message "[FireDAC][Phys][FB]conversion error from string ''".
There is no chance to change any parameter on the Change User page.

**Comment by juliomar** [comment]
algum campo está com valor vazio e está fazendo a conversão

**Comment by giovani7cruz** [comment]
mletzel try build the exemple, and verify if the problem occred with it.

**Comment by giovani7cruz** [comment]
mletzel, probably this problem has been fixed. Update the source code and test again.
