### ISSUE TITLE
Instalação do Usercontrol no Delphi 11

### ISSUE THREAD

**Issue by vitorserip** [infussolucoes/usercontrol-sd#36]
Ola!
Fiz algumas tentativas para instalar o usercontrol no delphi 11 mas encontrei alguns problemas. Há alguma atualização prevista?

**Comment by juliomar** [comment]
Quais os erros? consegue postar imagem e logs do instalador?
que saiba funciona no Alexandria

**Comment by giovani7cruz** [comment]
Olá, a princípio esta tudo ok, testei com diversos usuários. Podes atualizar os fontes e tentar novamente. Lembrar de excluir arquivos .dcu, .bpl e outros que sejam de instalações antigas do user Control.
