### ISSUE TITLE
Falha na manutenção do banco dados firebird DBXConn default values tables/fields

### ISSUE THREAD

**Issue by JTheiller** [infussolucoes/usercontrol-sd#38]
Ao usar o **DBXConn** com DB **Firebird**, utilizando dos **nomes de tabelas e campos padrões**, ocorre uma falha devido ao nome das tabelas **não estarem em maiúsculo**.

`CheckDB` está tentando adicionar os campos já existentes porque a rotina de busca a lista de campos esta com a lista vazia.
`UCFindFieldTable` -> `FConnection.GetFieldNames(Tablename, TempList);`

- Opção1: Desenvolvedor deve sobrescrever os nomes para maiúsculo direto no projeto.
```
UserControl1.TableUsers.TableName  := UpperCase(UserControl1.TableUsers.TableName);
UserControl1.TableRights.TableName := UpperCase(UserControl1.TableRights.TableName);
```

- Opção2: Ajustar fontes do componente para fazer esse ajuste se o banco for firebird.
```
procedure TUserControl.CheckBD;
begin
  if Assigned(UserSettings) then
  begin
    case UserSettings.BancoDados of
      Firebird: begin
                  FTableUsers.TableName := UpperCase(FTableUsers.TableName);
                  FTableRights.TableName := UpperCase(FTableRights.TableName);
                  FTableUsersLogged.TableName := UpperCase(FTableUsersLogged.TableName);
                end;
    end;
  end;

...
```

**Comment by juliomar** [comment]
Tu pode fazer um fork aplicar as mudanças e enviar um pull request e assim será integrado e testado.

**Comment by giovani7cruz** [comment]
Oi pessoal, vamos nos organizando para melhorar a atualização dos fontes.

**Comment by giovani7cruz** [comment]
Sugestão adicionada ao código. Obrigado!
