### ISSUE TITLE
erro ao instalar em XE3

### ISSUE THREAD

**Issue by jpnoronha** [infussolucoes/usercontrol-sd#5]
situação ao usar o instalador
desde já agradeço qualquer ajuda

segue log e ini do instalar
[log_Delphi_XE3.txt](https://github.com/infussolucoes/usercontrol-sd/files/293379/log_Delphi_XE3.txt)
[UCSWInstall.ini.txt](https://github.com/infussolucoes/usercontrol-sd/files/293382/UCSWInstall.ini.txt)

**Comment by StalinBR** [comment]
Fatal: F1026 File not found: 'IBX.IBDataBase.dcu'
Compilation failure
Erro ao compilar o pacote "pckUCIBXConn.dpk".

Tenta compilar o conector IB a parte.

**Comment by jpnoronha** [comment]
tentei, mas não funcionou.
entretanto passou a me dar novo erro na instalação. estou a enviar o log para analise.desde ja agradeço a atençao
Joao Paulo Noronha

Date: Mon, 27 Jun 2016 05:46:44 -0700

**Comment by infussolucoes** [comment]
Faça no seguinte teste:

No arquivo UCIBXConn

tem as seguintes linhas:
{$IF CompilerVersion >= 23}
  IBX.IBDataBase,
  IBX.IBQuery, 
  {$ELSE}
  IBDataBase,
  IBQuery,
  {$IFEND}

troque 23 por 24, salve e tente instalar novamente.

Caso não dê certo, deixe só  IBDataBase,
  IBQuery e tente instalar novamente.
