### ISSUE TITLE
ajuste na função EnviaEmailTp

### ISSUE THREAD

**Issue by Emers0n** [infussolucoes/usercontrol-sd#8]
Function TMailUserControl.EnviaEmailTp(Nome, Login, USenha, Email,
  Perfil: String; UCMSG: TUCMailMessage): Boolean;
var
  MailMsg: TAlSmtpClient;

{$IF CompilerVersion >= 23}
  MailRecipients: TALStringList;
  MailHeader: TALEmailHeader;
{$ELSE}
  MailRecipients : TStringlist;
  MailHeader : TALSMTPClientHeader;
{$IFEND}
begin
  Result := False;
  if Trim(Email) = '' then
    Exit;
  MailMsg := TAlSmtpClient.Create;

  {$IF CompilerVersion >= 23}
  // MailMsg.OnStatus       := OnStatus;
  MailRecipients := TALStringList.Create;
  MailHeader := TALEmailHeader.Create;
  {$ELSE}
  MailMsg                := TAlSmtpClient.Create;
  MailMsg.OnStatus       := OnStatus;
  MailRecipients         := TStringlist.Create;
  {$IFEND}

  MailHeader.From := EmailRemetente;
  MailHeader.SendTo := Email;
  MailHeader.ContentType := 'text/html';
  MailRecipients.Append(Email);
  MailHeader.Subject := UCMSG.Titulo;

  try
    try
      UCEMailForm := TUCEMailForm.Create(Self);
      UCEMailForm.lbStatus.Caption := '';
      UCEMailForm.Show;
      UCEMailForm.Update;

      MailMsg.SendMail(ServidorSMTP, FPorta, EmailRemetente, MailRecipients,
        Usuario, Senha, fAuthType, MailHeader.RawHeaderText,
        ParseMailMSG(Nome, Login, USenha, Email, Perfil, UCMSG.Mensagem.Text));

      UCEMailForm.Update;
      Result := True;
    except
      on e: Exception do
      begin
        UCEMailForm.Close;
        MessageDlg(e.Message, mtWarning, [mbok], 0);
        raise;
      end;
    end;
  finally
    FreeAndNil(MailMsg);
    FreeAndNil(MailHeader);
    FreeAndNil(MailRecipients);
    FreeAndNil(UCEMailForm);
  end;
end;

**Comment by infussolucoes** [comment]
Olá, não entendemos o problema. Podes passar mais detalhes?

**Comment by Emers0n** [comment]
A variável MailRecipients era do tipo talstrings mudei para talstringlist pois ao utilizar o metodo getcount enviando email estava dando a MSG de abstract error

**Comment by Emers0n** [comment]
A variável MailRecipients era do tipo talstrings mudei para talstringlist pois ao utilizar o metodo getcount enviando email estava dando a MSG de abstract error

**Comment by infussolucoes** [comment]
Certo, vamos aplicar ao projeto.

**Comment by infussolucoes** [comment]
Emers0n, subimos hoje as alterações.

Se puder, atualize seus fontes e verifique se a mesma foi aplicada.
Desde já agradecemos pela contribuição!

**Comment by infussolucoes** [comment]
Ajuste já aplicado.
