### ISSUE TITLE
envio de e-mail com o gmail

### ISSUE THREAD

**Issue by Emers0n** [infussolucoes/usercontrol-sd#9]
Olá bom dia.

Não estou conseguindo enviar e-email através de uma conta do Gmail

estou configurando da seguinte forma

smtp: smtp.gmail.com
porta: 465/587
AuthType: alsmtpClientAuthPlain
usuario : email@gmail.com

att

**Comment by linces** [comment]
O gmail atualmente vem configurando como padrão para não aceitar conexões externas ao smtp.. Vc precisa habilitar isso lá antes de utilizar o envio.

**Comment by ricar96** [comment]
Não consigo instalar o controle de usuário de um PC com 64-bit delphi 10,2 .... eu apreciaria me ajudar a realizar nesta ... como Delphi e o sistema é 64its o que eu faço é compilar e, em seguida, instalar, mas não Eu aparecer em qualquer paleta de componentes e da instalação me diz Erro ao compilar ou Pacote "pckUCDataConnector.dpk". Aguardo a sua resposta ... obrigado

**Comment by infussolucoes** [comment]
Exatamente, precisa dar algumas permissões no Gmail.

Neste artigo, mostra onde ir para confirurar o Gmail, além de mostrar um exemplo de envio
de e-mail com o ACBr.
http://showdelphi.com.br/como-configurar-o-envio-de-e-mail-com-o-gmail-no-acbrmail-delphi/
